# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
commands:
  build-docker-image:
    description: Build docker image for a model and update to GCR.
    parameters:
      project_name:
        type: string
      dockerfile_path:
        type: string
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            docker build -t << parameters.project_name >> -f << parameters.dockerfile_path >> .

jobs:
  welcome-jobs:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - build-docker-image:
          project_name: ext-devops
          dockerfile_path: ./contact_ranking.Dockerfile

workflows:
 welcome:
   jobs:
     - welcome-jobs:
         filters:
           branches:
             only:
               - master
